language: ruby


services:
  - mysql


bundle_args: --jobs=3 --retry=3


cache: bundler


before_install:
  - gem install bundler -v 2.0.2


before_script:
  - mysql -e 'CREATE DATABASE freemarket_sample_62a_test;'


script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
